### PR TITLE
Validate commit message and generated code

### PR DESCRIPTION
**Pull request by avishayt**
1. Ensure commit message is linked to an issue
2. Ensure that 'make generate' was run before committing

### CODE REVIEW

**Comment by hexfusion** [comment]
This makes sense internally but will not be very inviting for external contributors.

**Comment by mangelajo** [comment]
> This makes sense internally but will not be very inviting for external contributors.

I was thinking the same, but then I saw the plan is also to accept GitHub issue references. That would be fine by me.

**Comment by avishayt** [comment]
@hexfusion @mangelajo Ready to go

**Review by hexfusion — APPROVED** [review]
assuming all Jira tickets are open to public lgtm

**Pull request merged**
