### PR TITLE
MGMT-18170: Update documentation for certificate request

### PR DESCRIPTION
**Pull request by lkatalin**
This updates the docs based on changes in #529 .

As we want to support manually creating the CSR for some advanced users, this flow has been moved to a separate file.

### CODE REVIEW

**Comment by fzdarsky** [comment]
The "getting started" page is more a "quickstart" than a documentation. Means, it's meant to be highly opinionated (no description of alternatives) and concise ("do X to achieve Y", no detailed explanations). So basically, let's simply revert the section on getting the enrollment config to what it was originally (with the embedded certs), please.

More detailed documentation would belong into the building images, device provisioning, and device enrollment sections, respectively. However, even there we don't want to describe multiple options, unless there's strong reason and user demand. Therefore, let me complete these sections first, please, then we can review if something needs adding and where.

**Comment by lkatalin** [comment]
>The "getting started" page is more a "quickstart" than a documentation.

Okay, this makes sense.

> let's simply revert the section on getting the enrollment config to what it was originally

Do you mean the 4 part process using `apply -f`? Isn't that more complicated than what we want the user to do?

> even there we don't want to describe multiple options

Sounds good.

> let me complete these sections first, please, then we can review if something needs adding and where

This is fine as well. Should I then close this PR?

**Comment by lkatalin** [comment]
@fzdarsky Please take a look when you get the chance, I've got it back to your first simpler version plus updating the command flags.

**Review by fzdarsky — APPROVED** [review]

**Comment by lkatalin** [comment]
I am ready to merge this, however it seems that it cannot be merged because some tests are disabled.

**Comment by fzdarsky** [comment]
> I am ready to merge this, however it seems that it cannot be merged because some tests are disabled.

I'm afraid this is an issue I introduced with #570 that attempts to avoid running expensive code tests when only docs have changed. I've prepared PR #592 that should fix this and that we need to merge first.

**Pull request merged**
