### PR TITLE
Device sim labels

### PR DESCRIPTION
**Pull request by DakCrowder**
Adds ability to pass labels in a `key=value` format to the device simulator.  All devices spun up by the sim will share the passed labels.

### CODE REVIEW

**Review by fzdarsky — APPROVED** [review]

**Review by amir-yogev-gh — CHANGES_REQUESTED** [review]
Who asked for it?
I'm the feature owner for the simulator improvements and this was not discussed with me...

**Comment by mangelajo** [comment]
I think that in general we should add this to any devices from the device config, not only the simulator, that specific was discussed in many meetings. In that way, devices can have pre-defined config labels, that then can be used during enrollment phase, or device lifecycle.

**Comment by mangelajo** [comment]
> Who asked for it? I'm the feature owner for the simulator improvements and this was not discussed with me...

This is probably necessary to scale/test devices grouped by fleets.

**Comment by avishayt** [comment]
> This is probably necessary to scale/test devices grouped by fleets.
It might be useful but is not necessary.  It's possible to list ERs/devices and add labels to them.

**Comment by amir-yogev-gh** [comment]
"Probably" - is this the justification for a feature?

I'm complaining about the process, not the feature.
Where does it fit in the overall testing?
What are the alternatives?
Do you have the details to answer these questions?

No, this is unacceptable for me.

**Comment by mangelajo** [comment]
> "Probably" - is this the justification for a feature?
> 
> I'm complaining about the process, not the feature. Where does it fit in the overall testing? What are the alternatives? Do you have the details to answer these questions?
> 
> No, this is unacceptable for me.

Anyway, this is an internal development tool, more than a customer-side tool, right, or are we planning to support a device simulator? :)

**Comment by fzdarsky** [comment]
> Who asked for it? I'm the feature owner for the simulator improvements and this was not discussed with me...

The ask came from Perf&Scale testing (Yuri). It's required so we can run multiple dev sim instances in parallel and automatically label devices so they can be selected into different fleets.

**Review by amir-yogev-gh — APPROVED** [review]

**Pull request merged**
