### PR TITLE
MGMT-18351: Add version subcommand to cli

### PR DESCRIPTION
**Pull request by vraiti**
Adds version subcommand to CLI that uses metadata from git to determine the release.

Pretty much a direct copy of Microshift's mechanism for version logging: https://github.com/openshift/microshift/blob/main/pkg/cmd/version.go

### CODE REVIEW

**Review by avishayt — APPROVED** [review]

**Comment by avishayt** [comment]
LGTM, please rebase

**Comment by fzdarsky** [comment]
Plus run `gofmt -s -w .` to make the linter happy, please.

**Comment by fzdarsky** [comment]
In addition to rebasing, please also run `go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.0 run --fix` to make the linter happy :)

**Review by avishayt — DISMISSED** [review]
We don't have any version tags at the moment, so running any "make" command spams my console with the following message:
fatal: No names found, cannot describe anything.

**Comment by fzdarsky** [comment]
> We don't have any version tags at the moment, so running any "make" command spams my console with the following message: fatal: No names found, cannot describe anything.

Annoying, yes. At least the command outputs the right thing nevertheless.

**Review by fzdarsky — APPROVED** [review]

**Review by mangelajo — APPROVED** [review]

**Pull request merged**
