### PR TITLE
internal: move generated files into internal/api

### PR DESCRIPTION
**Pull request by hexfusion**
This PR moved generated files from internal/{server,client} as part of #72

### CODE REVIEW

**Comment by mangelajo** [comment]
Makes sense!

The linter is complaining, not sure what it means, is it complaining about the import order may be? 
```
internal/service/handler.go:8: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
	"github.com/flightctl/flightctl/internal/crypto"
internal/service/handler.go:9: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
	"github.com/flightctl/flightctl/internal/api/server"
cmd/flightctl-server/main.go:14: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
```

**Comment by fzdarsky** [comment]
> The linter is complaining, not sure what it means, is it complaining about the import order may be?

That's it, yes. Running `gci write --skip-generated .` would fix the order.

**Comment by mangelajo** [comment]
@hexfusion looks great, only two things:
1) Repo is configured to require signing of commits (with -S / gpg...)
2) Your PR is marked as draft. Is it really draft?

**Review by mangelajo — APPROVED** [review]
We need GPG signatures of the commits ':D

**Pull request merged**
